name: basic-demo
description: null
tags: null
initialize:
  plugins:
    mock-observations:
      path: "@grnsft/if-plugins"
      method: MockObservations
      global-config:
        timestamp-from: 2024-02-26T00:00
        timestamp-to: 2024-02-26T00:10
        duration: 60
        components:
          - cloud/instance-type: Standard_A1_v2
          - cloud/instance-type: Standard_A2_v2
        generators:
          common:
            cloud/vendor: azure
            cloud/region: uk-west
            geolocation: 37.7749,-122.4194
          randint:
            cpu/utilization:
              min: 1
              max: 99
    teads-curve:
      path: "@grnsft/if-unofficial-plugins"
      method: TeadsCurve
      global-config:
        interpolation: spline
    group-by:
      path: "builtin"
      method: GroupBy
    cloud-metadata:
      method: CloudInstanceMetadata
      path: "@grnsft/if-plugins"
    operational-carbon:
      path: "@grnsft/if-plugins"
      method: Multiply
      global-config:
        input-parameters: ["cpu/energy", "grid/carbon-intensity"]
        output-parameter: "cpu/carbon"
    watttime:
      path: "@grnsft/if-unofficial-plugins"
      method: WattTimeGridEmissions
      global-config:
        # username: ENV_WATT_TIME_USERNAME
        # password: ENV_WATT_TIME_PASSWORD
        username: manushak
        password: "@watt-time17"
tree:
  children:
    application:
      pipeline:
        - mock-observations
        # - group-by
        - cloud-metadata
        - teads-curve
        - watttime
        - operational-carbon
      defaults:
        grid/carbon-intensity: 250
        geolocation: 37.7749,-122.4194
      # config:
      #   group-by:
      #     group:
      #       - cloud/region
      #       - cloud/instance-type
      inputs:
        - timestamp: "2024-02-26 00:00:00"
          duration: 60
          cloud/instance-type: Standard_A1_v2
          cloud/vendor: azure
          cloud/region: uk-west
          geolocation: 37.7749,-122.4194
          cpu/utilization: 15
