name: ccf-demo
description: example impl invoking CCF model
tags:
initialize:
  plugins:
    ccf:
      method: CloudCarbonFootprint
      path: "@grnsft/if-unofficial-plugins"
tree:
  children:
    child:
      pipeline:
        - ccf
      defaults:
        cloud/vendor: "aws"
        cloud/instance-type: "m5n.large"
      inputs:
        - timestamp: 2023-07-06T00:00 # [KEYWORD] [NO-SUBFIELDS] time when measurement occurred
          duration: 1
          cpu/utilization: 10
